### ISSUE TITLE
Default value

### ISSUE THREAD

**Issue by charlesfries** [jelhan/ember-local-storage-decorator#18]
I'm looking to replace `ember-local-storage` in my project with this addon. My question is: is there a way to specify a default value for a localstorage key? `ember-local-storage` has the concept of storage classes:

```js
import StorageObject from 'ember-local-storage/local/object';

const Storage = StorageObject.extend();

Storage.reopenClass({
  initialState() {
    return {
      theme: 'light',
    }; // <-- if the localstorage key does not exist, this object is used as the default value
  },
});

export default Storage;
```

Is is possible to do something like this?

**Comment by jelhan** [comment]
Hello @charlesfries,

`ember-local-storage-decorator` supports default values _per usage_:

```js
const Klass = class {
  @localStorage foo = 'bar';
}

window.localStorage.clean();

const klass = new Klass();
klass.foo === 'bar'; // true
window.localStorage.getItem('foo'); // null
```

Somehow I missed to cover that in the documentation. But you can see an example in the tests: https://github.com/jelhan/ember-local-storage-decorator/blob/a28b41876f2fbc285c4b7327a84b7075e2928ae0/tests/unit/decorators/local-storage-test.js#L15-L31

_Global_ defaults are _not_ supported. This is by design. Value stored in local storage should be the source of truth in my opinion. If you want to share some default values between classed and only maintain at one place, you could export them from a utility module:

```js
// app/utils/defaults.js

export {
  FOO: 'bar',
};
```

```js
// app/components/my-component.js

import Component from '@glimmer/component';
import localStorage from 'ember-local-storage-decorator';
import { FOO } from '../utils/defaults.js';

export default class MyComponent extends Component {
  @localStorage
  foo = FOO;
}
```

I'm sorry that I haven't had time to reply earlier.

Best
jelhan
